#!/bin/bash

NUMBER=3
COMMAND=""
FLAG=0
WAIT=1

function usage {
  cat <<EOM
Usage: $(basename "$0") [OPTION]...
  -c COMMAND  for Command
  -n NUMBER   for Number of Execution
  -w WAIT     for Waiting Time
  -h          Display Help
EOM
  exit 1
}

while getopts ":n:w:c:h" optKey; do
  case "$optKey" in
    c)
      COMMAND="${OPTARG}"
      FLAG=1
      ;;
    n)
      NUMBER=${OPTARG}
      ;;
    w)
      WAIT=${OPTARG}
      ;;
    '-h'|'--help'|* )
      usage
      ;;
  esac
done

if [ "${FLAG}" -eq 0 ];then
  usage
  exit 1
fi

N='^[0-9]+$'
if ! [[ "${NUMBER}" =~ ${N} ]] ; then
  usage
  exit 1
fi

for num in `seq 1 "${NUMBER}"`
do
  echo "${num}: ${COMMAND}"
  echo "= = = = ="
  ${COMMAND}
  echo ${?}
  echo
  wait
  sleep ${WAIT}
done

exit 0
